version: '2'
services:
    consul:
        image: consul
        command: agent -ui -bind=${CFS_CONFIG_CONSUL_SERVER} -retry-join={CFS_CONFIG_CONSUL_JOIN}
        network_mode: host
    cfs-connector:
        image: commonms/cfs-connector
        ports:
            - "8080:8080"
        depends_on:
            - consul