version: '2'
services:
    consul:
        image: consul
        command: agent -ui -server -bind=${CFS_CONFIG_CONSUL_SERVER} -bootstrap-expect=1
        network_mode: host
    mongo:
        image: mongo
    git2consul:
        image: cimpress/git2consul
        command: --config-file /etc/git2consul.d/config.json
        volumes:
            - /c/Users/git2consul.d:/etc/git2consul.d
        dependes_on:
            - consul
    mongo-express:
        image: mongo-express
        ports:
            - "8081:8081"
        depends_on:
            - mongo
    cfs-core:
        image: commonms/cfs-core
        ports:
            - "8080:8080"
        depends_on:
            - consul
            - mongo
