version: '2'
services:
    consul:
        image: consul
        command: agent -ui -server -bind=${CFS_CONFIG_CONSUL_SERVER} -bootstrap-expect=1 -client=${CFS_CONFIG_CONSUL_SERVER}
        network_mode: host
    git2consul:
        image: knieschraube/git2consul
        entrypoint: sh wait_for_consul_leader.sh
        environment:
            - CONSUL_ENDPOINT=${CFS_CONFIG_CONSUL_SERVER}
            - COMMAND=--config-file /etc/git2consul.d/config.json
        network_mode: host
        volumes:
            - /c/Users/git2consul.d:/etc/git2consul.d
        depends_on:
            - consul
    cfs-connector:
        image: commonms/cfs-connector:0.1.0
        environment:
            - CFS_CONFIG_CONSUL_SERVER
        network_mode: host
        depends_on:
            - consul
            - git2consul
    cfs-core:
        image: commonms/cfs-core:0.1.0
        environment:
            - CFS_CONFIG_CONSUL_SERVER
        network_mode: host
        depends_on:
            - consul
            - git2consul
            - cfs-connector
            - mongo
    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=${CFS_CONFIG_CONSUL_SERVER}
        network_mode: host
        depends_on:
            - mongo
    mongo:
        image: mongo
        network_mode: host
