version: '2'
services:
    consul:
        image: consul
        command: agent -ui -server -bind=${CFS_CONFIG_CONSUL_SERVER} -bootstrap-expect=1 -client=${CFS_CONFIG_CONSUL_SERVER}
        network_mode: host
    git2consul:
        image: commonms/git2consul
        entrypoint: sh wait_for_consul_leader.sh
        environment:
            - CONSUL_ENDPOINT=${CFS_CONFIG_CONSUL_SERVER}
            - COMMAND=--config-file /etc/git2consul.d/config.json
        network_mode: host
        volumes:
            - /c/Users/${USERNAME}/git/cfs-config:/etc/git2consul.d
        depends_on:
            - consul
    mysql:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=cabrono2
            - MYSQL_DATABASE=cfs-admin-db
            - MYSQL_USER=cfs
            - MYSQL_PASSWORD=cfspass
        network_mode: host
    mongo:
        image: mongo
        network_mode: host
    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=${CFS_CONFIG_CONSUL_SERVER}
        ports:
            - "8281:8081"
        depends_on:
            - mongo
    cfs-connector-reuters:
        image: commonms/cfs-connector-reuters
        environment:
            - CFS_CONFIG_CONSUL_SERVER
            - _JAVA_OPTIONS=${JAVA_OPTS}
        network_mode: host
        mem_limit: 512M
        depends_on:
            - consul
            - git2consul
    cfs-connector-bloomberg:
        image: commonms/cfs-connector-bloomberg
        environment:
            - CFS_CONFIG_CONSUL_SERVER
            - _JAVA_OPTIONS=${JAVA_OPTS}
        network_mode: host
        mem_limit: 512M
        depends_on:
            - consul
            - git2consul
    cfs-connector-infobolsa:
        image: commonms/cfs-connector-infobolsa
        environment:
            - CFS_CONFIG_CONSUL_SERVER
            - _JAVA_OPTIONS=${JAVA_OPTS}
        network_mode: host
        mem_limit: 512M
        depends_on:
            - consul
            - git2consul
    cfs-connector-mongodb:
        image: commonms/cfs-connector-mongodb
        environment:
            - CFS_CONFIG_CONSUL_SERVER
            - CFS_MONGO_HOST=${CFS_CONFIG_CONSUL_SERVER}
            - _JAVA_OPTIONS=${JAVA_OPTS}
        network_mode: host
        mem_limit: 512M
        depends_on:
            - consul
            - git2consul
            - mongo
    cfs-core:
        image: commonms/cfs-core
        environment:
            - CFS_CONFIG_CONSUL_SERVER
        network_mode: host
        mem_limit: 512M
        depends_on:
            - consul
            - git2consul
            - cfs-admin
            - cfs-monitor
            - cfs-connector-reuters
            - cfs-connector-bloomberg
            - cfs-connector-infobolsa
            - cfs-connector-mongodb
    cfs-admin:
        image: commonms/cfs-admin
        environment:
            - CFS_CONFIG_CONSUL_SERVER
            - CFS_MYSQL_HOST=${CFS_CONFIG_CONSUL_SERVER}
        network_mode: host
        mem_limit: 512M
        depends_on:
            - consul
            - git2consul
            - mysql
    cfs-monitor:
        image: commonms/cfs-monitor
        environment:
            - CFS_CONFIG_CONSUL_SERVER
            - CFS_MONGO_HOST=${CFS_CONFIG_CONSUL_SERVER}
        network_mode: host
        mem_limit: 512M
        depends_on:
            - consul
            - git2consul
            - mongo
